import React, { useState } from "react";
import { Pressable, Text, TextInput, View } from "react-native";
import { useFormMessage } from "../../../forms/useFormMessage";
import { parseRequiredDateYYYYMMDD, parseRequiredPositiveInteger } from "../../../forms/validation";
import { colors, spacing } from "../../../../design/theme";
import type { ProtectedWorkoutDraft } from "../../../../services/supabase/onboardingService";
import { screenStyles } from "../../screenStyles";
import type { OnboardingStepProps } from "./BoxerBasicsStep";

function OptionButton({ active, label, onPress }: { active: boolean; label: string; onPress: () => void }) {
  return (
    <Pressable accessibilityRole="button" onPress={onPress} style={[screenStyles.quietButton, active ? { borderColor: colors.blueIQ } : null]}>
      <Text style={screenStyles.quietButtonText}>{label}</Text>
    </Pressable>
  );
}

export function ProtectedScheduleStep({ draft, updateDraft }: OnboardingStepProps) {
  const [type, setType] = useState<ProtectedWorkoutDraft["type"]>("technical_session");
  const [date, setDate] = useState(draft.protectedSchedule[0]?.date ?? "");
  const [durationMinutes, setDurationMinutes] = useState("45");
  const [intensity, setIntensity] = useState<ProtectedWorkoutDraft["intensity"]>("moderate");
  const { message: error, runWithMessage } = useFormMessage("Anchor could not be added.");

  const addAnchor = () => {
    void runWithMessage(async () => {
      updateDraft((current) => ({
        ...current,
        protectedSchedule: [
          ...current.protectedSchedule,
          {
            type,
            date: parseRequiredDateYYYYMMDD(date, "Anchor date"),
            durationMinutes: parseRequiredPositiveInteger(durationMinutes, "Anchor duration"),
            intensity,
            note: "Protected boxing anchor"
          }
        ]
      }));
    });
  };

  return (
    <View style={{ gap: spacing.md }}>
      <Text style={screenStyles.sectionTitle}>Protected boxing anchors</Text>
      <Text style={screenStyles.subtle}>These are coach or life anchors the engine should protect. Sparring is treated as a protected commitment, not generated by CornerIQ.</Text>
      {error ? <Text style={[screenStyles.subtle, { color: colors.redCorner }]}>{error}</Text> : null}
      {draft.protectedSchedule.map((workout) => (
        <Text key={`${workout.type}_${workout.date}_${workout.durationMinutes}`} style={screenStyles.body}>
          {workout.type.replace(/_/g, " ")} - {workout.date} - {workout.durationMinutes} min
        </Text>
      ))}
      <View style={{ flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }}>
        {(["technical_session", "pads_mitts", "bag_work", "sparring", "roadwork", "coach_assigned_strength", "travel", "recovery_day"] as const).map((option) => (
          <OptionButton active={type === option} key={option} label={option.replace(/_/g, " ")} onPress={() => setType(option)} />
        ))}
      </View>
      <TextInput onChangeText={setDate} placeholder="Date YYYY-MM-DD" placeholderTextColor={colors.wrap} style={screenStyles.input} value={date} />
      <TextInput keyboardType="number-pad" onChangeText={setDurationMinutes} placeholder="Duration minutes" placeholderTextColor={colors.wrap} style={screenStyles.input} value={durationMinutes} />
      <View style={{ flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }}>
        {(["easy", "moderate", "hard", "max"] as const).map((option) => <OptionButton active={intensity === option} key={option} label={option} onPress={() => setIntensity(option)} />)}
      </View>
      <Pressable accessibilityRole="button" onPress={addAnchor} style={screenStyles.button}>
        <Text style={screenStyles.buttonText}>Add anchor</Text>
      </Pressable>
    </View>
  );
}
