import React from "react";
import { Pressable, Text, View } from "react-native";
import type { RecentLogsViewModel, TrainViewModel } from "../../engine/core/types";
import { ActionCard } from "../../design/components/ActionCard";
import { DisclosureCard } from "../../design/components/DisclosureCard";
import { EngineCard } from "../../design/components/EngineCard";
import { EmptyState } from "../../design/components/EmptyState";
import { LuminousScreen, MetricTile, ScreenHeader, type LuminousAccent } from "../../design/components/LuminousScreen";
import { RiskBanner } from "../../design/components/RiskBanner";
import { SectionTabs, type SectionTabItem } from "../../design/components/SectionTabs";
import { TopActionCard } from "../../design/components/TopActionCard";
import { colors, spacing } from "../../design/theme";
import type { QuickLogActions } from "../../hooks/useQuickLogs";
import type { WorkoutCompletionActions } from "../../hooks/useWorkoutCompletion";
import { ProtectedWorkoutLogCard } from "./logging/LogCards";
import { screenStyles } from "./screenStyles";
import { ExerciseHistoryPanel } from "./train/ExerciseHistoryPanel";
import { WorkoutDetailPanel } from "./train/WorkoutDetailPanel";

type TrainSection = "today" | "workout" | "history" | "progression";

const trainSections: readonly SectionTabItem<TrainSection>[] = [
  { key: "today", label: "Today" },
  { key: "workout", label: "Workout" },
  { key: "history", label: "Exercise History" },
  { key: "progression", label: "Progression" }
];

export interface TrainScreenProps {
  busy: boolean;
  completionActions?: WorkoutCompletionActions | undefined;
  completionMessage?: string | null | undefined;
  quickLogs: QuickLogActions;
  recentLogs: RecentLogsViewModel;
  viewModel: TrainViewModel;
}

function ManualTrainingLoggerSection({ busy, quickLogs }: { busy: boolean; quickLogs: QuickLogActions }) {
  const [open, setOpen] = React.useState(false);
  return (
    <View style={{ gap: spacing.lg }} testID="train-manual-logger-section">
      <EngineCard>
        <View style={{ gap: spacing.sm }}>
          <Text style={screenStyles.sectionTitle}>Log your own training</Text>
          <Text style={screenStyles.subtle}>Use this for boxing class, roadwork, sparring, or strength work not generated by CornerIQ.</Text>
          <Pressable accessibilityRole="button" accessibilityState={{ selected: open }} onPress={() => setOpen((value) => !value)} style={screenStyles.quietButton}>
            <Text style={screenStyles.quietButtonText}>{open ? "Hide manual training log" : "Show manual training log"}</Text>
          </Pressable>
        </View>
      </EngineCard>
      {open ? <ProtectedWorkoutLogCard actions={quickLogs} busy={busy} /> : null}
    </View>
  );
}

function sessionPurpose(session: TrainViewModel["sessionCards"][number]): string {
  if (session.intensity === "easy" || session.intensity === "recovery") {
    return "Purpose: keep the body ready for boxing without chasing fatigue.";
  }
  const protectedWork = session.protects[0];
  return protectedWork ? `Purpose: support ${protectedWork.toLowerCase()} while keeping boxing quality first.` : "Purpose: build support capacity around protected boxing.";
}

function flowAccent(index: number): LuminousAccent {
  return (["blue", "purple", "orange", "green"] as const)[index % 4] ?? "blue";
}

function sessionMetricValue(viewModel: TrainViewModel): string {
  const count = viewModel.sessionCards.length;
  if (count === 0) {
    return "No session";
  }
  return `${count} session${count === 1 ? "" : "s"}`;
}

function fuelMetricValue(viewModel: TrainViewModel): string {
  const demand = viewModel.sessionCards[0]?.fuelDemand;
  if (!demand) {
    return "Fuel check";
  }
  return `${demand.charAt(0).toUpperCase()}${demand.slice(1)} fuel`;
}

function WorkoutFlowPreview({ session }: { session: TrainViewModel["sessionCards"][number] }) {
  return (
    <EngineCard>
      <View style={{ gap: spacing.lg }}>
        <Text style={screenStyles.sectionTitle}>Flow</Text>
        {session.prescription.slice(0, 4).map((item, index) => (
          <View key={`flow:${session.title}:${index}`} style={{ alignItems: "center", flexDirection: "row", gap: spacing.md }}>
            <View
              style={{
                alignItems: "center",
                backgroundColor: "rgba(255, 255, 255, 0.06)",
                borderColor:
                  flowAccent(index) === "blue"
                    ? "rgba(39, 206, 241, 0.36)"
                    : flowAccent(index) === "purple"
                      ? "rgba(150, 87, 245, 0.34)"
                      : flowAccent(index) === "orange"
                        ? "rgba(255, 148, 72, 0.34)"
                        : "rgba(56, 226, 138, 0.34)",
                borderRadius: 16,
                borderWidth: 1,
                height: 48,
                justifyContent: "center",
                width: 48
              }}
            >
              <Text style={{ color: colors.canvas, fontSize: 16, fontWeight: "800" }}>{String(index + 1).padStart(2, "0")}</Text>
            </View>
            <View style={{ flex: 1, gap: spacing.xs }}>
              <Text style={screenStyles.body}>{item}</Text>
              <Text style={screenStyles.subtle}>boxing support work</Text>
            </View>
          </View>
        ))}
      </View>
    </EngineCard>
  );
}

export function TrainScreen({ busy, completionActions, completionMessage, quickLogs, recentLogs, viewModel }: TrainScreenProps) {
  const [section, setSection] = React.useState<TrainSection>("today");
  return (
    <LuminousScreen testID="train-screen">
      <ScreenHeader eyebrow="Workout" title={viewModel.title} />
      <TopActionCard
        accent="purple"
        optional={viewModel.topAction.optional}
        primaryAction={viewModel.topAction.primaryAction}
        purpose={viewModel.topAction.purpose}
        testID="train-top-action-card"
        title={viewModel.topAction.title}
        why={viewModel.topAction.why}
      />
      <View style={{ flexDirection: "row", flexWrap: "wrap", gap: spacing.md }}>
        <MetricTile accent="purple" label="Session" meta={viewModel.todayRole.status.replace(/_/g, " ")} value={sessionMetricValue(viewModel)} />
        <MetricTile accent="orange" label="Fuel" meta="Carbs + water" value={fuelMetricValue(viewModel)} />
      </View>
      <SectionTabs items={trainSections} value={section} onChange={setSection} />
      {viewModel.riskSummary.length > 0 ? (
        <RiskBanner title="Training safety check" message="Training changes stay blocked or reduced while these safety notes are active." tone="critical">
          <View style={{ gap: spacing.xs }}>
            {viewModel.riskSummary.map((risk, index) => <Text key={`train-risk:${index}`} style={screenStyles.body}>{risk}</Text>)}
          </View>
        </RiskBanner>
      ) : null}
      {section === "today" ? (
        <View style={{ gap: spacing.lg }} testID="train-today-section">
          {viewModel.sessionCards[0] ? <WorkoutFlowPreview session={viewModel.sessionCards[0]} /> : null}
          {viewModel.sessionCards.length > 0 ? viewModel.sessionCards.map((session, index) => (
            <View key={`today-session:${session.title}:${index}`} testID={index === 0 ? "train-main-workout-command" : undefined}>
              <ActionCard
                action="Open workout, then log result."
                actionLabel="Open workout"
                detailLabel="why / safety"
                detailSummary="Plan context, fuel notes, and safety detail stay here unless a hard stop is active."
                highlights={session.prescription.slice(0, 6)}
                onAction={() => setSection("workout")}
                status={`${session.durationMinutes} min, ${session.intensity}. Fuel: ${viewModel.preSessionFuelHint}`}
                subtitle={sessionPurpose(session)}
                title={session.title}
              >
                <View style={{ gap: spacing.sm }}>
                  <Text style={screenStyles.body}>Why: {session.why}</Text>
                  <Text style={screenStyles.subtle}>{viewModel.postSessionFuelHint}</Text>
                  <Text style={screenStyles.subtle}>{viewModel.hydrationHint}</Text>
                  {session.modifications.map((item, itemIndex) => <Text key={`modify:${index}:${itemIndex}`} style={screenStyles.subtle}>Modify: {item}</Text>)}
                  {session.protects.map((item, itemIndex) => <Text key={`protects:${index}:${itemIndex}`} style={screenStyles.subtle}>Protects: {item}</Text>)}
                </View>
              </ActionCard>
            </View>
          )) : (
            <EmptyState title="No generated support today" message="No generated support is due. That matters because future work should not be pulled forward from Plan. Log coach-led boxing if it happens." />
          )}
          <DisclosureCard title="Plan context" summary={`${viewModel.todayRole.summary} ${viewModel.protectedAnchorSummary}`}>
            <View style={{ gap: spacing.sm }}>
              <Text style={screenStyles.body}>{viewModel.blockPhase.replaceAll("_", " ")} - {viewModel.blockGoal}</Text>
              <Text style={screenStyles.body}>{viewModel.blockExplanation}</Text>
              <Text style={screenStyles.subtle}>{viewModel.todayRole.explanation}</Text>
              <Text style={screenStyles.subtle}>{viewModel.analytics.nextBestTrainingAction}</Text>
            </View>
          </DisclosureCard>
          {viewModel.cycleTrainingDecision.status !== "none" ? (
          <EngineCard>
            <View style={{ gap: spacing.sm }}>
              <Text style={screenStyles.sectionTitle}>Cycle context</Text>
              <Text style={screenStyles.body}>{viewModel.cycleTrainingDecision.summary}</Text>
              <Text style={screenStyles.subtle}>{viewModel.cycleTrainingDecision.action}</Text>
            </View>
          </EngineCard>
          ) : null}
        </View>
      ) : null}
      {section === "workout" ? (
        <View style={{ gap: spacing.lg }} testID="train-workout-section">
          {viewModel.detailedTodaySessions.length > 0 ? viewModel.detailedTodaySessions.map((session) => (
            session.detail ? (
              <WorkoutDetailPanel busy={busy} completionActions={completionActions} completionMessage={completionMessage} key={session.generatedSessionId} session={session.detail} />
            ) : (
              <EngineCard key={session.generatedSessionId}>
                <View style={{ gap: spacing.sm }}>
                  <Text style={screenStyles.sectionTitle}>{session.title}</Text>
                  {session.firstExercises.map((item, index) => <Text key={`first-exercise:${session.generatedSessionId}:${index}`} style={screenStyles.body}>{item}</Text>)}
                  <Text style={screenStyles.body}>{session.whyThisMattersForBoxing}</Text>
                  {session.safetyNotes.map((note, index) => <Text key={`fallback-safety:${session.generatedSessionId}:${index}`} style={screenStyles.subtle}>{note}</Text>)}
                </View>
              </EngineCard>
            )
          )) : <EmptyState title="No workout detail today" message="No generated support detail is due today. That matters because future work should not be pulled forward from Plan. Log coach-led boxing if it happens; otherwise this section can wait." />}
          <ManualTrainingLoggerSection busy={busy} quickLogs={quickLogs} />
        </View>
      ) : null}
      {section === "history" ? (
        <View style={{ gap: spacing.lg }} testID="train-history-section">
          <EngineCard>
            <ExerciseHistoryPanel history={viewModel.exerciseHistory} />
          </EngineCard>
          <EngineCard>
            <View style={{ gap: spacing.sm }}>
              <Text style={screenStyles.sectionTitle}>Recent training</Text>
              {recentLogs.training.length > 0 ? recentLogs.training.map((item, index) => <Text key={`recent-training:${index}`} style={screenStyles.body}>{item}</Text>) : <Text style={screenStyles.body}>No recent training logs yet.</Text>}
              {viewModel.analytics.lastCompletedSession ? <Text style={screenStyles.subtle}>Last completed: {viewModel.analytics.lastCompletedSession}</Text> : null}
              {viewModel.analytics.lastSkippedSession ? <Text style={screenStyles.subtle}>Last skipped: {viewModel.analytics.lastSkippedSession}</Text> : null}
              <Text style={screenStyles.subtle}>Completions last 7 days: {viewModel.analytics.completionCountLast7Days}</Text>
              <Text style={screenStyles.subtle}>Exercise results last 7 days: {viewModel.analytics.exerciseResultCountLast7Days}</Text>
              <Text style={screenStyles.subtle}>{viewModel.analytics.consistencySummary}</Text>
            </View>
          </EngineCard>
        </View>
      ) : null}
      {section === "progression" ? (
        <View style={{ gap: spacing.lg }} testID="train-progression-section">
          <EngineCard>
            <View style={{ gap: spacing.sm }}>
              <Text style={screenStyles.sectionTitle}>Progression / next best action</Text>
              <Text style={screenStyles.body}>{viewModel.progressionSummary.summary}</Text>
              <Text style={screenStyles.subtle}>{viewModel.progressionSummary.status}: {viewModel.progressionSummary.why}</Text>
              <Text style={screenStyles.callout}>{viewModel.analytics.nextBestTrainingAction}</Text>
              <Text style={screenStyles.subtle}>Generated completed/skipped: {viewModel.analytics.generatedSessionsCompleted}/{viewModel.analytics.generatedSessionsSkipped}</Text>
              <Text style={screenStyles.subtle}>Pain flags: {viewModel.analytics.painFlagCount}</Text>
              <Text style={screenStyles.subtle}>Exercise status completed/partial/prescribed only: {viewModel.analytics.completedResultCount}/{viewModel.analytics.partialResultCount}/{viewModel.analytics.prescribedOnlyCount}</Text>
              {viewModel.analytics.averageSessionRpe === null ? null : <Text style={screenStyles.subtle}>Average session RPE: {viewModel.analytics.averageSessionRpe}</Text>}
              {viewModel.analytics.averageExerciseRpe === null ? null : <Text style={screenStyles.subtle}>Average exercise RPE: {viewModel.analytics.averageExerciseRpe}</Text>}
              {viewModel.analytics.mostRecentExerciseResultSummary ? <Text style={screenStyles.subtle}>Recent exercise: {viewModel.analytics.mostRecentExerciseResultSummary}</Text> : null}
              {viewModel.analytics.mostRepeatedExercise ? <Text style={screenStyles.subtle}>Repeated exercise: {viewModel.analytics.mostRepeatedExercise}</Text> : null}
              {viewModel.analytics.latestStrengthExerciseSummary ? <Text style={screenStyles.subtle}>Strength actual: {viewModel.analytics.latestStrengthExerciseSummary}</Text> : null}
              {viewModel.analytics.painFlagExercises.map((exercise, index) => <Text key={`pain-flag-exercise:${index}`} style={screenStyles.subtle}>Pain flag exercise: {exercise}</Text>)}
              <Text style={screenStyles.subtle}>Today's completion will influence next week's dose, but no numeric load progression is inferred from notes.</Text>
            </View>
          </EngineCard>
        </View>
      ) : null}
    </LuminousScreen>
  );
}
