import React from "react";
import { Pressable, ScrollView, Text, View } from "react-native";
import type { RecentLogsViewModel, TrainViewModel } from "../../engine/core/types";
import { ActionCard } from "../../design/components/ActionCard";
import { EngineCard } from "../../design/components/EngineCard";
import { EmptyState } from "../../design/components/EmptyState";
import { RiskBanner } from "../../design/components/RiskBanner";
import { SectionTabs, type SectionTabItem } from "../../design/components/SectionTabs";
import { TopActionCard } from "../../design/components/TopActionCard";
import { spacing } from "../../design/theme";
import type { QuickLogActions } from "../../hooks/useQuickLogs";
import type { WorkoutCompletionActions } from "../../hooks/useWorkoutCompletion";
import { ProtectedWorkoutLogCard } from "./logging/LogCards";
import { screenStyles } from "./screenStyles";
import { ExerciseHistoryPanel } from "./train/ExerciseHistoryPanel";
import { WorkoutDetailPanel } from "./train/WorkoutDetailPanel";

type TrainSection = "today" | "workout" | "history" | "progression";

const trainSections: readonly SectionTabItem<TrainSection>[] = [
  { key: "today", label: "Today" },
  { key: "workout", label: "Workout" },
  { key: "history", label: "Exercise History" },
  { key: "progression", label: "Progression" }
];

export interface TrainScreenProps {
  busy: boolean;
  completionActions?: WorkoutCompletionActions | undefined;
  completionMessage?: string | null | undefined;
  quickLogs: QuickLogActions;
  recentLogs: RecentLogsViewModel;
  viewModel: TrainViewModel;
}

function ManualTrainingLoggerSection({ busy, quickLogs }: { busy: boolean; quickLogs: QuickLogActions }) {
  const [open, setOpen] = React.useState(false);
  return (
    <View style={{ gap: spacing.lg }} testID="train-manual-logger-section">
      <EngineCard>
        <View style={{ gap: spacing.sm }}>
          <Text style={screenStyles.sectionTitle}>Log your own training</Text>
          <Text style={screenStyles.subtle}>Use this for boxing class, roadwork, sparring, or strength work not generated by CornerIQ.</Text>
          <Pressable accessibilityRole="button" accessibilityState={{ selected: open }} onPress={() => setOpen((value) => !value)} style={screenStyles.quietButton}>
            <Text style={screenStyles.quietButtonText}>{open ? "Hide manual training log" : "Show manual training log"}</Text>
          </Pressable>
        </View>
      </EngineCard>
      {open ? <ProtectedWorkoutLogCard actions={quickLogs} busy={busy} /> : null}
    </View>
  );
}

export function TrainScreen({ busy, completionActions, completionMessage, quickLogs, recentLogs, viewModel }: TrainScreenProps) {
  const [section, setSection] = React.useState<TrainSection>("today");
  return (
    <ScrollView style={screenStyles.screen} contentContainerStyle={screenStyles.content} testID="train-screen">
      <Text style={screenStyles.title}>{viewModel.title}</Text>
      <TopActionCard
        optional={viewModel.topAction.optional}
        primaryAction={viewModel.topAction.primaryAction}
        purpose={viewModel.topAction.purpose}
        testID="train-top-action-card"
        title={viewModel.topAction.title}
        why={viewModel.topAction.why}
      />
      <SectionTabs items={trainSections} value={section} onChange={setSection} />
      {viewModel.riskSummary.length > 0 ? (
        <RiskBanner title="Training safety check" message="Training changes stay blocked or reduced while these safety notes are active." tone="critical">
          <View style={{ gap: spacing.xs }}>
            {viewModel.riskSummary.map((risk) => <Text key={risk} style={screenStyles.body}>{risk}</Text>)}
          </View>
        </RiskBanner>
      ) : null}
      {section === "today" ? (
        <View style={{ gap: spacing.lg }} testID="train-today-section">
          {viewModel.sessionCards.length > 0 ? viewModel.sessionCards.map((session) => (
            <ActionCard
              action="Open workout, then log completed or skipped."
              actionLabel="Open workout"
              detailLabel="why / safety"
              detailSummary="Concrete prescription lines are shown first; optional why and safety stay collapsed."
              highlights={session.prescription.slice(0, 5)}
              key={session.title}
              onAction={() => setSection("workout")}
              status={`${session.durationMinutes} min, ${session.intensity}, fuel demand ${session.fuelDemand}.`}
              title={session.title}
              why={session.why}
            >
              <View style={{ gap: spacing.sm }}>
                {session.modifications.map((item) => <Text key={item} style={screenStyles.subtle}>Modify: {item}</Text>)}
                {session.protects.map((item) => <Text key={item} style={screenStyles.subtle}>Protects: {item}</Text>)}
              </View>
            </ActionCard>
          )) : (
            <EmptyState title="No generated support today" message="No generated support is due. That matters because future work should not be pulled forward from Plan. Log coach-led boxing if it happens." />
          )}
          <EngineCard>
            <View style={{ gap: spacing.sm }}>
              <Text style={screenStyles.sectionTitle}>Today's training decision</Text>
              <Text style={screenStyles.body}>{viewModel.todaySummary}</Text>
              <Text style={screenStyles.body}>{viewModel.protectedAnchorSummary}</Text>
              <Text style={screenStyles.callout}>{viewModel.analytics.nextBestTrainingAction}</Text>
            </View>
          </EngineCard>
          <EngineCard>
            <View style={{ gap: spacing.sm }}>
              <Text style={screenStyles.sectionTitle}>Block context</Text>
              <Text style={screenStyles.body}>{viewModel.blockPhase.replaceAll("_", " ")} - {viewModel.blockGoal}</Text>
              <Text style={screenStyles.body}>{viewModel.blockExplanation}</Text>
              <Text style={screenStyles.callout}>{viewModel.todayRole.summary}</Text>
              <Text style={screenStyles.subtle}>{viewModel.todayRole.explanation}</Text>
            </View>
          </EngineCard>
          <EngineCard>
            <View style={{ gap: spacing.sm }}>
              <Text style={screenStyles.sectionTitle}>Fuel handoff</Text>
              <Text style={screenStyles.body}>{viewModel.preSessionFuelHint}</Text>
              <Text style={screenStyles.body}>{viewModel.postSessionFuelHint}</Text>
              <Text style={screenStyles.subtle}>{viewModel.hydrationHint}</Text>
            </View>
          </EngineCard>
          <EngineCard>
            <View style={{ gap: spacing.sm }}>
              <Text style={screenStyles.sectionTitle}>Cycle training decision</Text>
              <Text style={screenStyles.body}>{viewModel.cycleTrainingDecision.summary}</Text>
              <Text style={screenStyles.subtle}>{viewModel.cycleTrainingDecision.action}</Text>
            </View>
          </EngineCard>
        </View>
      ) : null}
      {section === "workout" ? (
        <View style={{ gap: spacing.lg }} testID="train-workout-section">
          {viewModel.detailedTodaySessions.length > 0 ? viewModel.detailedTodaySessions.map((session) => (
            <EngineCard key={session.generatedSessionId}>
              {session.detail ? (
                <WorkoutDetailPanel busy={busy} completionActions={completionActions} completionMessage={completionMessage} session={session.detail} />
              ) : (
                <View style={{ gap: spacing.sm }}>
                  <Text style={screenStyles.sectionTitle}>{session.title}</Text>
                  {session.firstExercises.map((item) => <Text key={item} style={screenStyles.body}>{item}</Text>)}
                  <Text style={screenStyles.body}>{session.whyThisMattersForBoxing}</Text>
                  {session.safetyNotes.map((note) => <Text key={note} style={screenStyles.subtle}>{note}</Text>)}
                </View>
              )}
            </EngineCard>
          )) : <EmptyState title="No workout detail today" message="No generated support detail is due today. That matters because future work should not be pulled forward from Plan. Log coach-led boxing if it happens; otherwise this section can wait." />}
          <ManualTrainingLoggerSection busy={busy} quickLogs={quickLogs} />
        </View>
      ) : null}
      {section === "history" ? (
        <View style={{ gap: spacing.lg }} testID="train-history-section">
          <EngineCard>
            <ExerciseHistoryPanel history={viewModel.exerciseHistory} />
          </EngineCard>
          <EngineCard>
            <View style={{ gap: spacing.sm }}>
              <Text style={screenStyles.sectionTitle}>Recent training</Text>
              {recentLogs.training.length > 0 ? recentLogs.training.map((item) => <Text key={item} style={screenStyles.body}>{item}</Text>) : <Text style={screenStyles.body}>No recent training logs yet.</Text>}
              {viewModel.analytics.lastCompletedSession ? <Text style={screenStyles.subtle}>Last completed: {viewModel.analytics.lastCompletedSession}</Text> : null}
              {viewModel.analytics.lastSkippedSession ? <Text style={screenStyles.subtle}>Last skipped: {viewModel.analytics.lastSkippedSession}</Text> : null}
              <Text style={screenStyles.subtle}>Completions last 7 days: {viewModel.analytics.completionCountLast7Days}</Text>
              <Text style={screenStyles.subtle}>Exercise results last 7 days: {viewModel.analytics.exerciseResultCountLast7Days}</Text>
              <Text style={screenStyles.subtle}>{viewModel.analytics.consistencySummary}</Text>
            </View>
          </EngineCard>
        </View>
      ) : null}
      {section === "progression" ? (
        <View style={{ gap: spacing.lg }} testID="train-progression-section">
          <EngineCard>
            <View style={{ gap: spacing.sm }}>
              <Text style={screenStyles.sectionTitle}>Progression / next best action</Text>
              <Text style={screenStyles.body}>{viewModel.progressionSummary.summary}</Text>
              <Text style={screenStyles.subtle}>{viewModel.progressionSummary.status}: {viewModel.progressionSummary.why}</Text>
              <Text style={screenStyles.callout}>{viewModel.analytics.nextBestTrainingAction}</Text>
              <Text style={screenStyles.subtle}>Generated completed/skipped: {viewModel.analytics.generatedSessionsCompleted}/{viewModel.analytics.generatedSessionsSkipped}</Text>
              <Text style={screenStyles.subtle}>Pain flags: {viewModel.analytics.painFlagCount}</Text>
              <Text style={screenStyles.subtle}>Exercise status completed/partial/prescribed only: {viewModel.analytics.completedResultCount}/{viewModel.analytics.partialResultCount}/{viewModel.analytics.prescribedOnlyCount}</Text>
              {viewModel.analytics.averageSessionRpe === null ? null : <Text style={screenStyles.subtle}>Average session RPE: {viewModel.analytics.averageSessionRpe}</Text>}
              {viewModel.analytics.averageExerciseRpe === null ? null : <Text style={screenStyles.subtle}>Average exercise RPE: {viewModel.analytics.averageExerciseRpe}</Text>}
              {viewModel.analytics.mostRecentExerciseResultSummary ? <Text style={screenStyles.subtle}>Recent exercise: {viewModel.analytics.mostRecentExerciseResultSummary}</Text> : null}
              {viewModel.analytics.mostRepeatedExercise ? <Text style={screenStyles.subtle}>Repeated exercise: {viewModel.analytics.mostRepeatedExercise}</Text> : null}
              {viewModel.analytics.latestStrengthExerciseSummary ? <Text style={screenStyles.subtle}>Strength actual: {viewModel.analytics.latestStrengthExerciseSummary}</Text> : null}
              {viewModel.analytics.painFlagExercises.map((exercise) => <Text key={exercise} style={screenStyles.subtle}>Pain flag exercise: {exercise}</Text>)}
              <Text style={screenStyles.subtle}>Today's completion will influence next week's dose, but no numeric load progression is inferred from notes.</Text>
            </View>
          </EngineCard>
        </View>
      ) : null}
    </ScrollView>
  );
}
